on: pull_request
jobs:
  foo:
    runs-on: ubuntu-22.04

    steps:
      - name: haha
        env:
          PULL_NUMBER: 1
        run: |
          curl -X POST \
            "https://api.github.com/repos/$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY/pulls/${{ env.PULL_NUMBER }}/reviews"
