name: "deploy"

on: workflow_dispatch

jobs:
  dev:
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      - name: say hello
        run: echo hello

      - name: say hi
        run: echo hi 
  
  stage:
    runs-on: ubuntu-22.04
    environment: stage
    # needs: dev

    steps:
      - name: say hello
        run: exit 1
