name: "deploy"

on: workflow_dispatch

jobs:
  dev:
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      - name: say hello
        run: exit 1
  
  stage:
    runs-on: ubuntu-22.04
    environment: stage
    needs: dev

    steps:
      - name: say hello
        run: exit 1
